[versions]
kotlin = "2.2.21"
spring-boot = "3.5.6"

[libraries]
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

micrometer-core = { module = "io.micrometer:micrometer-core" }
micrometer-registry-otlp = { module = "io.micrometer:micrometer-registry-otlp" }
micrometer-tracing = { module = "io.micrometer:micrometer-tracing" }
micrometer-tracing-bridge-otel = { module = "io.micrometer:micrometer-tracing-bridge-otel" }

mockk = { module = "io.mockk:mockk", version = "1.14.7" }
mockk-spring = { module = "com.ninja-squad:springmockk", version = "5.0.1" }

opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp" }
opentelemetry-logback-appender = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0", version = "2.23.0-alpha" }

org-asciidoctor-jvm-convert-gradle-plugin = { module = "org.asciidoctor.jvm.convert:org.asciidoctor.jvm.convert.gradle.plugin", version = "3.3.2" }

postgresql = { module = "org.postgresql:postgresql" }

querydsl-apt = { module = "com.querydsl:querydsl-apt" }
querydsl-jpa = { module = "com.querydsl:querydsl-jpa" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons" }
spring-restdocs-asciidoctor = { module = "org.springframework.restdocs:spring-restdocs-asciidoctor" }
spring-restdocs-mockmvc = { module = "org.springframework.restdocs:spring-restdocs-mockmvc" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-tx = { module = "org.springframework:spring-tx" }

testcontainers-grafana = { module = "org.testcontainers:grafana" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql" }

[plugins]
application = { id = "application" }

java-platform = { id = "java-platform" }
java-test-fixtures = { id = "java-test-fixtures" }

kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-jvm = { id = "com.example.kotlin-jvm" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.4" }

org-asciidoctor-jvm-convert = { id = "com.example.org-asciidoctor-jvm-convert" }

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }